### PR TITLE
Added phenotype to broadcast. Going to play russian roulette and let …

### LINKED ISSUE #2816: GPL-556 BUG: Phenotype not propagated to WLWH
**Describe the bug**
Lighthouse crawler is creating samples in SS correctly however  test result (+ve, -ve or void) not propagated to  MLWH

**To Reproduce**

EG http://sequencescape.psd.sanger.ac.uk/samples/4536523

Supplier Sample Name: | MILK-4CA03B
Phenotype: | negative

however

SELECT DISTINCT
sample.name
,sample.supplier_name
,sample.phenotype
,submission_study.name AS 'submission_study'
FROM
sample
JOIN stock_resource stock ON stock.id_sample_tmp=sample.id_sample_tmp
JOIN study submission_study ON stock.id_study_tmp=submission_study.id_study_tmp
WHERE submission_study.name = 'Heron Project'
AND phenotype IS NOT NULL
AND SUBSTRING(sample.supplier_name,1,4) IN ('MILK', 'ALDP', 'QEUH', 'CBAZ')
ORDER BY stock.created;

0 records

**Expected behaviour**
Should be mostly + ves 

**Additional context**
From slack "not broadcasting, the attr is not in a white list"

### PR DESCRIPTION
**Pull request by stevieing**
…travis tell me what tests are failing. I won. It passed.

Can I add a test for this?

Closes #2816

Changes proposed in this pull request:

* add phenotype to sample broadcast to the warehouse
*
* ...

### CODE REVIEW

**Comment by JamesGlover** [comment]
I think there are tests for some of the other messenger classes. Will see if I can point you too them once I'm back

**Comment by JamesGlover** [comment]
Tests for the SampleIO
`spec/models/api/sample_io_spec.rb`
It uses `expect(rendered_json).to include_json(expected_json)` rather than a direct match, hence why the tests continue to pass is other fields are added.

**Comment by KatyTaylor** [comment]
(To ask Steve when he's back) Was a data migration done following this issue to backfill phenotype data in the MLWH?

Issue raised by Cristina, probably related to this. RT ticket - https://rt.sanger.ac.uk/Ticket/Display.html?id=704099&results=fde3caffed89db48b0f87faf0af4c242

Just wondering if there are more samples out there affected by the same issue, but not in her list.

**Comment by KatyTaylor** [comment]
```
SELECT description AS 'Root Sample ID', supplier_name AS 'COG UK ID', phenotype AS 'Result', sanger_sample_id
FROM sample 
WHERE sanger_sample_id LIKE 'Heron%'
  AND phenotype IS NULL -- 203,135
```

returns 203,135 records, and I don't think it should return any.

**Pull request merged**
