### PR TITLE
Gpl 225 cherrypick fluidigm bug

### PR DESCRIPTION
**Pull request by KatyTaylor**
Symptom of this bug was that wells and, later, QC results, were being recorded against the wrong plate. Neil and Steve did a data fix for this recently.

The problem happened at the final cherrypick stage in the 'Cherrypick for Fluidigm' pipeline where 2 (SNP Type) plates were being picked onto 1 Fluidigm chip:
- This happens on a Tecan robot. 
- You put the 2 source plates in beds on the left, and the Fluidigm chip on the right. 
- The robot is run by a file that Fluidigm provided for this specific chip type, and it always picks the top plate (bed SCRC1) into rows A, C, E etc, and the bottom plate (SCRC2) into rows B, D, F etc.
- Sequencescape generates the layout for the Fluidigm chip, deciding which samples are in which wells. 
- So the person putting the plates on the robot has to put them the right way round, otherwise the resulting plate has a different layout to how Sequencescape thinks it is. 
- They decide which way round to put the plates based on the 'Source plates' section at the top of the worksheet printed out from the Batch page.
- The order the plates are in in this section on the worksheet was not determined in a useful way by Sequencescape - they were just ordered based on the id of their Transfer Request records
- This meant that the worksheet was 'correct' if the transfer requests and the plates were created in a consistent order, and 'incorrect' if not.
- I have changed it to order the source plates on the worksheet based on the order they are in the Fluidigm chip - so they should always be in the correct order for the robot now
- The bed verification page uses the same code so should be consistent with the worksheet ('@robot_verification.expected_layout' in 'robot_verifications_controller' uses 'tecan_layout_plate_barcodes' in 'tecan_behaviour')

Manual steps to reproduce the issue:
- Generate 2 plates using the UAT tab - note which order they were created in
- Go to 'Create submission' page, make a submission for 'Cherrypick for Fluidigm', selecting template 'Fluidigm 192-24'
- Add an order, select 'From plate and wells', pasting in the plate barcode that was created **second**
- Save order and build submission
- Repeat creating the submission for the plate barcode that was created **first**
- Go to the Pipelines tab and the Cherrypick for Fluidigm pipeline
- Select the 2 submissions you just made and submit a batch
- Step through all the steps in the pipeline, cherrypicking from plate to plate, always doing the 2 submissions together in a batch
- When you've done the final cherrypick you should end up with a Fluidigm plate
- Go to the final batch page and click 'print worksheet'
- Existing, wrong behaviour: The plate listed as 'SCRC1' is in row 'B', and 'SCRC2' in row 'A'
- Desired behaviour: The plate listed as 'SCRC1' is in row 'A', and 'SCRC2' in row 'B'

### CODE REVIEW

**Comment by pjvv** [comment]
Love the detail, thanks Katy!

**Comment by KatyTaylor** [comment]
@emrojo I changed it to sort using the 'row order' on the Map records, instead of the 'description' ('S001' etc.)
Unfortunately it meant I had to make the tests dependent on having real plates, barcodes etc in the setup, and meant the barcodes had to be proper formats etc.
Does it look ok to you?

Thanks

**Comment by KatyTaylor** [comment]
For future reference:
The structure of the 'data_object' referenced by 'tecan_file_generation.rb' is something like as follows:

> {
"user"=>"admin", 
"time"=>Thu, 19 Dec 2019 14:18:12 GMT +00:00, 
"source"=>{
  "DN9000064O"=>{"name"=>"ABgene 0765", "plate_size"=>96}, 
  "DN9000065P"=>{"name"=>"ABgene 0765", "plate_size"=>96}
  }, 
"destination"=>{
  "DN9000066Q"=>{
    "name"=>"ABgene 0800", 
    "plate_size"=>192, 
    "mapping"=>[
      {"src_well"=>["DN9000064O", "A1"], "dst_well"=>"S001", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B1"], "dst_well"=>"S025", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C1"], "dst_well"=>"S049", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D1"], "dst_well"=>"S073", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E1"], "dst_well"=>"S097", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F1"], "dst_well"=>"S121", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G1"], "dst_well"=>"S145", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H1"], "dst_well"=>"S169", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A2"], "dst_well"=>"S002", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B2"], "dst_well"=>"S026", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C2"], "dst_well"=>"S050", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D2"], "dst_well"=>"S074", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E2"], "dst_well"=>"S098", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F2"], "dst_well"=>"S122", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G2"], "dst_well"=>"S146", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H2"], "dst_well"=>"S170", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A3"], "dst_well"=>"S003", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B3"], "dst_well"=>"S027", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C3"], "dst_well"=>"S051", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D3"], "dst_well"=>"S075", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E3"], "dst_well"=>"S099", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F3"], "dst_well"=>"S123", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G3"], "dst_well"=>"S147", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H3"], "dst_well"=>"S171", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A4"], "dst_well"=>"S004", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B4"], "dst_well"=>"S028", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C4"], "dst_well"=>"S052", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D4"], "dst_well"=>"S076", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E4"], "dst_well"=>"S100", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F4"], "dst_well"=>"S124", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G4"], "dst_well"=>"S148", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H4"], "dst_well"=>"S172", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A5"], "dst_well"=>"S005", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B5"], "dst_well"=>"S029", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C5"], "dst_well"=>"S053", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D5"], "dst_well"=>"S077", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E5"], "dst_well"=>"S101", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F5"], "dst_well"=>"S125", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G5"], "dst_well"=>"S149", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H5"], "dst_well"=>"S173", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A6"], "dst_well"=>"S006", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B6"], "dst_well"=>"S030", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C6"], "dst_well"=>"S054", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D6"], "dst_well"=>"S078", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E6"], "dst_well"=>"S102", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F6"], "dst_well"=>"S126", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G6"], "dst_well"=>"S150", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H6"], "dst_well"=>"S174", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A7"], "dst_well"=>"S007", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B7"], "dst_well"=>"S031", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C7"], "dst_well"=>"S055", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D7"], "dst_well"=>"S079", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E7"], "dst_well"=>"S103", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F7"], "dst_well"=>"S127", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G7"], "dst_well"=>"S151", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H7"], "dst_well"=>"S175", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A8"], "dst_well"=>"S008", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B8"], "dst_well"=>"S032", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C8"], "dst_well"=>"S056", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D8"], "dst_well"=>"S080", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E8"], "dst_well"=>"S104", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F8"], "dst_well"=>"S128", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G8"], "dst_well"=>"S152", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H8"], "dst_well"=>"S176", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A9"], "dst_well"=>"S009", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B9"], "dst_well"=>"S033", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C9"], "dst_well"=>"S057", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D9"], "dst_well"=>"S081", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E9"], "dst_well"=>"S105", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F9"], "dst_well"=>"S129", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G9"], "dst_well"=>"S153", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H9"], "dst_well"=>"S177", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A10"], "dst_well"=>"S010", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B10"], "dst_well"=>"S034", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C10"], "dst_well"=>"S058", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D10"], "dst_well"=>"S082", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E10"], "dst_well"=>"S106", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F10"], "dst_well"=>"S130", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G10"], "dst_well"=>"S154", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H10"], "dst_well"=>"S178", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A11"], "dst_well"=>"S011", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B11"], "dst_well"=>"S035", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C11"], "dst_well"=>"S059", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D11"], "dst_well"=>"S083", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E11"], "dst_well"=>"S107", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F11"], "dst_well"=>"S131", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G11"], "dst_well"=>"S155", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H11"], "dst_well"=>"S179", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "A12"], "dst_well"=>"S012", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "B12"], "dst_well"=>"S036", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "C12"], "dst_well"=>"S060", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "D12"], "dst_well"=>"S084", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "E12"], "dst_well"=>"S108", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "F12"], "dst_well"=>"S132", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "G12"], "dst_well"=>"S156", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000064O", "H12"], "dst_well"=>"S180", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A1"], "dst_well"=>"S013", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B1"], "dst_well"=>"S037", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C1"], "dst_well"=>"S061", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D1"], "dst_well"=>"S085", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E1"], "dst_well"=>"S109", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F1"], "dst_well"=>"S133", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G1"], "dst_well"=>"S157", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H1"], "dst_well"=>"S181", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A2"], "dst_well"=>"S014", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B2"], "dst_well"=>"S038", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C2"], "dst_well"=>"S062", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D2"], "dst_well"=>"S086", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E2"], "dst_well"=>"S110", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F2"], "dst_well"=>"S134", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G2"], "dst_well"=>"S158", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H2"], "dst_well"=>"S182", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A3"], "dst_well"=>"S015", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B3"], "dst_well"=>"S039", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C3"], "dst_well"=>"S063", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D3"], "dst_well"=>"S087", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E3"], "dst_well"=>"S111", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F3"], "dst_well"=>"S135", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G3"], "dst_well"=>"S159", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H3"], "dst_well"=>"S183", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A4"], "dst_well"=>"S016", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B4"], "dst_well"=>"S040", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C4"], "dst_well"=>"S064", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D4"], "dst_well"=>"S088", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E4"], "dst_well"=>"S112", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F4"], "dst_well"=>"S136", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G4"], "dst_well"=>"S160", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H4"], "dst_well"=>"S184", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A5"], "dst_well"=>"S017", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B5"], "dst_well"=>"S041", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C5"], "dst_well"=>"S065", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D5"], "dst_well"=>"S089", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E5"], "dst_well"=>"S113", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F5"], "dst_well"=>"S137", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G5"], "dst_well"=>"S161", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H5"], "dst_well"=>"S185", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A6"], "dst_well"=>"S018", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B6"], "dst_well"=>"S042", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C6"], "dst_well"=>"S066", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D6"], "dst_well"=>"S090", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E6"], "dst_well"=>"S114", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F6"], "dst_well"=>"S138", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G6"], "dst_well"=>"S162", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H6"], "dst_well"=>"S186", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A7"], "dst_well"=>"S019", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B7"], "dst_well"=>"S043", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C7"], "dst_well"=>"S067", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D7"], "dst_well"=>"S091", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E7"], "dst_well"=>"S115", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F7"], "dst_well"=>"S139", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G7"], "dst_well"=>"S163", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H7"], "dst_well"=>"S187", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A8"], "dst_well"=>"S020", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B8"], "dst_well"=>"S044", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C8"], "dst_well"=>"S068", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D8"], "dst_well"=>"S092", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E8"], "dst_well"=>"S116", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F8"], "dst_well"=>"S140", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G8"], "dst_well"=>"S164", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H8"], "dst_well"=>"S188", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A9"], "dst_well"=>"S021", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B9"], "dst_well"=>"S045", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C9"], "dst_well"=>"S069", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D9"], "dst_well"=>"S093", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E9"], "dst_well"=>"S117", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F9"], "dst_well"=>"S141", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G9"], "dst_well"=>"S165", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H9"], "dst_well"=>"S189", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A10"], "dst_well"=>"S022", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B10"], "dst_well"=>"S046", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C10"], "dst_well"=>"S070", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D10"], "dst_well"=>"S094", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E10"], "dst_well"=>"S118", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F10"], "dst_well"=>"S142", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G10"], "dst_well"=>"S166", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H10"], "dst_well"=>"S190", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A11"], "dst_well"=>"S023", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B11"], "dst_well"=>"S047", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C11"], "dst_well"=>"S071", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D11"], "dst_well"=>"S095", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E11"], "dst_well"=>"S119", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F11"], "dst_well"=>"S143", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G11"], "dst_well"=>"S167", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H11"], "dst_well"=>"S191", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "A12"], "dst_well"=>"S024", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "B12"], "dst_well"=>"S048", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "C12"], "dst_well"=>"S072", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "D12"], "dst_well"=>"S096", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "E12"], "dst_well"=>"S120", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "F12"], "dst_well"=>"S144", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "G12"], "dst_well"=>"S168", "volume"=>13.0, "buffer_volume"=>0.0}, 
      {"src_well"=>["DN9000065P", "H12"], "dst_well"=>"S192", "volume"=>13.0, "buffer_volume"=>0.0}
    ]
  }
}
}

**Comment by KatyTaylor** [comment]
Something else for safekeeping -
To be able to progress on the 'Create submission' page after selecting 'Cherrypick for Fluidigm' as the template, I had to modify the 'Cherrypick for Fluidigm' database record in the submission templates table - submission parameters field. The diff between prod and UAT2 was this:

Screenshot 2020-01-02 at 13 15 40

where green is prod, and also the end result in UAT2

**Pull request merged**
